DIG-80395 image cache
TotalWineLabs/imageproxy pull request #8
Opened 2023-10-02 19:13 UTC by yashtrivedi04

Adding a 400 check since requests such as the following are getting through and corrupting the cache
<img width="1081" alt="Screenshot 2023-10-02 at 3 12 21 PM" src="https://github.com/TotalWineLabs/imageproxy/assets/9142514/79e13cbe-e7c4-43b4-aabb-c1c88ce161c7">

2023-10-02 19:18 UTC, sforsberg requested changes
I know I said this made sense in slack, but looking at it again I think we need to split the check.

2023-10-02 19:18 UTC, sforsberg commented on imageproxy.go
>  		return nil, err
Looking at this again, we may want to split this into 2 separate if conditions. Leave the previous condition as it is, and move the new check to it's own if. From there we can return a crafted error response that includes at minimum the status code. With the way it is now, what may happen is that the error will be `nil` and the response will be `nil`, which can make it difficult to debug what is going wrong in these scenarios.

2023-10-03 14:58 UTC, sforsberg requested changes
Some considerations to ensure we provide the logged error with enough information for debugging purposes.

2023-10-03 14:58 UTC, sforsberg commented on imageproxy.go
> +			return nil, errors.ErrCustom.New("Bad Request (400) received when retrieving image.")
For both of these new errors we should include the URL that failed in the message (for ease of debugging) unless the URL is shown along with the error returned. 

For this one in particular, we could also use `errors.ErrBadRequestReason.New()` to add the statusCode the error.

2023-10-03 14:58 UTC, sforsberg commented on imageproxy.go
> +			errors.ErrCustom.New(fmt.Sprintf("Error received when retrieving image. Status: %d", resp.StatusCode))
Similar to the above, we should include the URL in the error message. Additionally, we could set the error code in the error struct, using [`error.SetCode(resp.StatusCode)`](https://github.com/TotalWineLabs/go-common/blob/8eefabd660eddb84856ea464d3445bc980fe1150/src/errors/errors.go#L67) this should make the logged error more consistent with other services that are using `go-common/errors`.

Something like:
```go
error := errors.ErrCustom.New(fmt.Sprintf("Error received when retrieving image: %s",  u.String())
error.SetCode(resp.StatusCode)
return nil, error
```

2023-10-03 16:25 UTC, sforsberg approved these changes

2023-10-04 15:13 UTC, kenhkelly requested changes

2023-10-04 15:13 UTC, kenhkelly commented on imageproxy.go
> +	"github.com/totalwinelabs/go-common/src/errors"
We don't want to use this in this library

2023-10-04 15:13 UTC, kenhkelly commented on imageproxy.go
> +		return nil, imageError
This should be similar to how the should304 returns

2023-10-04 18:48 UTC, sforsberg requested changes

2023-10-04 18:48 UTC, sforsberg commented on imageproxy.go
> +	if resp.StatusCode >= 404 {
Let's change this to `400` to include any 4XX response

2023-10-04 18:55 UTC, sforsberg approved these changes

2023-10-04 19:11 UTC, kenhkelly approved these changes

2023-10-04 19:12 UTC, merged